require('reflect-metadata')
export { AuthorizerData } from './types'
export { Deny } from './src/authorizer/deny'
export { Allow } from './src/authorizer/allow'
export { Effect } from './src/authorizer/effect'
// export { AuthorizerParams } from './types/index'
// export { ScopeAuthorizer } from './src/authorizer/scope'
export { Authorizer } from './src/authorizer/authorizer'
// export { Permissions } from './src/authorizer/permissions'
export { registerTypeGraphqlGlobalMiddleware } from './src/middleware/register.middleware'
